require("msotgia.native.options")
require("msotgia.native.statuscolumn")
require("msotgia.native.winbar")
require("msotgia.native.netrw")
require("msotgia.native.lsp")
require("msotgia.native.themes")
